package gui.swing.cellActionApproved;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


public class PanelAction extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form PanelAction
     */
    public PanelAction(boolean type) {
        initComponents(type);
    }

    public void initEvent(TableActionEvent event, int row) {
        cmdApproved.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onApproved(row);
            }
        });
        cmdDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
        cmdEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        cmdDeny.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				event.onDeny(row);
			}
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(boolean type) {

        cmdApproved = new gui.swing.cellAction.ActionButton();
        cmdDeny = new ActionButton();
        cmdEdit = new gui.swing.cellAction.ActionButton();
        cmdDelete = new gui.swing.cellAction.ActionButton();


        cmdApproved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/swing//cellActionApproved/approved.png"))); // NOI18N
        
        cmdDeny.setIcon(new ImageIcon(getClass().getResource("/gui/swing//cellActionApproved/deny.png")));
        
        cmdDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/swing//cellActionApproved/delete.png"))); // NOI18N

        cmdEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/swing//cellActionApproved/edit.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        if (!type) {
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(164, Short.MAX_VALUE)
        			.addComponent(cmdEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cmdDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cmdApproved, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(cmdDeny, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(164))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(134, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(cmdEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cmdDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cmdApproved, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cmdDeny, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(135, Short.MAX_VALUE))
        );
        
        }
    
        else {
        	layout.setHorizontalGroup(
                	layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(layout.createSequentialGroup()
                			.addContainerGap(164, Short.MAX_VALUE)
                	
                			.addComponent(cmdEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addComponent(cmdDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                			.addGap(164))
                );
                layout.setVerticalGroup(
                	layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(layout.createSequentialGroup()
                			.addContainerGap(134, Short.MAX_VALUE)
                			.addGroup(layout.createParallelGroup(Alignment.LEADING)
                				.addComponent(cmdEdit, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                				.addComponent(cmdDelete, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                			.addContainerGap(135, Short.MAX_VALUE))
                );
        
        }
        
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.swing.cellAction.ActionButton cmdApproved;
    private gui.swing.cellAction.ActionButton cmdEdit;
    private gui.swing.cellAction.ActionButton cmdDelete;
    private ActionButton cmdDeny;
    // End of variables declaration//GEN-END:variables
}
